name: neuralclothsim2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pytorch3d
  - defaults
dependencies:
  - python=3.10.14
  - pytorch=2.1.0
  - torchvision=0.15.2 
  - pytorch-cuda=12.1
  - fvcore 
  - iopath
  - pytorch3d
  - packaging
  - tensorboard
