name: neuralclothsim
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - fvcore
  - pytorch3d
dependencies:
  - python=3.10
  - pytorch-cuda=11.8
  - pytorch=2.3.1
  - torchvision=0.18.1
  - fvcore
  - pip=24.0
  - tensorboard=2.12.1
  - matplotlib
  - imageio
  - natsort
  - configargparse
  - pytorch3d=0.7.7
  - pip:
    - iopath==0.1.10
